# this is a copy of ../conda/environment_linux.yaml for docker forbidden path outside

name: melon-dev
channels:
  - conda-forge
  - defaults
  - melon-rpc
dependencies:
  - gcc =8.5 # [linux]
  - gxx =8.5 # [linux]
  - sysroot_linux-64=2.17 # [linux]
  - cmake =3.19.1
  - make
  - gflags =2.2.2
  - leveldb =1.22
  - protobuf =3.12.4 # includes Protobuf compiler, C++ headers, Python libraries
  - openssl =1.1.1
  - zlib
  - gperftools=2.9.1