name: melon-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - clang # [osx]
  - clangxx #   [osx]
  - gflags =2.2.2
  - leveldb =1.22
  - protobuf >=3.9.2, <=3.19.1
  - openssl =1.1.1
  - zlib
  - gperftools=2.9.1
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark